name: Release Building

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:

    runs-on: macos-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Build
        run: |
          brew install automake
          brew install autoconf
          brew install libtool
          make VERSION="${GITHUB_REF_NAME}" BUILD_NUMBER="${GITHUB_RUN_NUMBER}" release
          make release-dmg 
          shasum -a 256 build/Release/ShadowsocksX-NG.dmg > build/Release/ShadowsocksX-NG.dmg.checksum

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ShadowsocksX-NG
          path: |
            build/Release/ShadowsocksX-NG.dmg
            build/Release/ShadowsocksX-NG.dmg.checksum

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: ShadowsocksX-NG Fork ${{ github.ref_name }}
          generate_release_notes: true
          files: |
            build/Release/ShadowsocksX-NG.dmg
            build/Release/ShadowsocksX-NG.dmg.checksum
